{% set name = "qcfractal" %}
{% set version = "0.5.5" %}
{% set sha256 = "de631589b74c1e96cab5fb85218d09f348eee89c70b06c15d54c0afe8b431653" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - qcfractal-server = qcfractal.cli.qcfractal_server:main
    - qcfractal-manager = qcfractal.cli.qcfractal_manager:main
    - qcfractal-template=qcfractal.cli.qcfractal_template_generator:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy
    - pandas
    - mongodb
    - tornado
    - requests
    - bcrypt
    - pyyaml
    - cryptography
    - pydantic >=0.20
    - mongoengine
    - qcengine >=0.6.2
    - qcelemental >=0.3.3

test:
  requires:
    - pytest
    - pytest-cov
    - codecov
  imports:
    - qcfractal

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A distributed compute and database platform for quantum chemistry.

extra:
    recipe-maintainers:
        - dgasmith
        - lnaden
