{% set name = "qcfractal" %}
{% set version = "0.10.0" %}
{% set sha256 = "9895f8ddb723c54c64e5921fd8e0c2541b7f03696d93be29e13e0dc4b7189f35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - qcfractal-server = qcfractal.cli.qcfractal_server:main
    - qcfractal-manager = qcfractal.cli.qcfractal_manager:main
    - qcfractal-template=qcfractal.cli.qcfractal_template_generator:main
    - qcfractal-dashboard=qcfractal.cli.qcfractal_dashboard:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy
    - pandas
    - tornado
    - requests
    - bcrypt
    - pyyaml >=5.1
    - cryptography
    - pydantic >=0.32.0
    - msgpack-python>=0.6.1
    - tqdm


    # Server dependencies
    - sqlalchemy >=1.3
    - psycopg2 >=2.7
    - postgresql
    - alembic
    
    # QCArchive dependencies
    - qcengine >=0.9.0
    - qcelemental >=0.6.0
    
    # Plotly and py3dmol are Portal dependencies

test:
  requires:
    - pytest
    - pytest-cov
    - codecov
  imports:
    - qcfractal

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A distributed compute and database platform for quantum chemistry.

extra:
    recipe-maintainers:
        - dgasmith
        - lnaden
